export const REQUEST_TOP_EVENTS = 'REQUEST_TOP_EVENTS';
export const RECEIVE_TOP_EVENTS = 'RECEIVE_TOP_EVENTS';
export const TOP_EVENTS_LOAD_FAILURE = 'TOP_EVENTS_LOAD_FAILURE';

export const REQUEST_TOP_PROPERTIES = 'REQUEST_TOP_PROPERTIES';
export const RECEIVE_TOP_PROPERTIES = 'RECEIVE_TOP_PROPERTIES';
export const TOP_PROPERTIES_LOAD_FAILURE = 'TOP_PROPERTIES_LOAD_FAILURE';

export const REQUEST_TOP_PROPERTY_VALUES = 'REQUEST_TOP_PROPERTY_VALUES';
export const RECEIVE_TOP_PROPERTY_VALUES = 'RECEIVE_TOP_PROPERTY_VALUES';
export const TOP_PROPERTY_VALUES_LOAD_FAILURE = 'TOP_PROPERTY_VALUES_LOAD_FAILURE';
